#!/usr/bin/env perl

use File::Spec;
use Cwd 'abs_path';

sub main {

	install("_root/etc/zshenv", "sudo");

	if (`uname -s` =~ /Darwin/) {
		install("_home/Library/KeyBindings/DefaultKeyBinding.dict");
		install("_home/Library/Application Support/TextMate/KeyBindings.dict");

		install("_root/etc/paths.d/000-mybin", "sudo");
		install("_root/etc/paths.d/100-macports", "sudo");
		install("_root/etc/paths.d/500-default", "sudo");
		remove("/etc/paths", "sudo");
		
		`defaults write com.apple.Terminal FocusFollowsMouse -string YES`;
		
		`defaults write org.x.X11 sync_clipboard_to_pasteboard true`;
    `defaults write org.x.X11 sync_pasteboard true`;
    `defaults write org.x.X11 sync_pasteboard_to_clipboard true`;
    `defaults write org.x.X11 sync_pasteboard_to_primary true`;
    `defaults write org.x.X11 sync_primary_on_select true`;
    `defaults write org.x.X11 wm_click_through true`;
    `defaults write org.x.X11 wm_ffm true`;
    `defaults write org.x.X11 wm_focus_on_new_window true`;
    
	}

}

sub install {
	my ($source_path, $sudo) = @_;

	$home = $ENV{'HOME'};
	my ($volume, $base_path, $file_name) = File::Spec->splitpath($source_path);
	$dest_base_path = $base_path;
	$dest_base_path =~ s|^_home/|$home/|;
	$dest_base_path =~ s|^_root/|/|;	
	$dest_path = "$dest_base_path$file_name";

	$pretty_path = $dest_path;
	$pretty_path =~ s|^$home/|~/|;

	unless (-d "$dest_base_path") {
		`$sudo mkdir -p $dest_base_path` or die "\nmkdir: $!";
	}

	if (!(-e "$dest_path") || `diff -w "$source_path" "$dest_path"`) {
		print "Installing $pretty_path\n";
		`$sudo cp -i "$source_path" "$dest_path"`;
	}
	else
	{
		print "Skipping $pretty_path\n";
	}
}

sub remove {
	my ($path, $sudo) = @_;
	
	if (-e $path) {
		print "Removing $path\n";
		`$sudo mv $path $path.old`;
	}
	
}

main
